name: Sphinx Document

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
        docker build -t jspecify-sphinx docs
        docker run --rm -v $GITHUB_WORKSPACE/docs:/docs jspecify-sphinx make html
        docker run --rm -v $GITHUB_WORKSPACE/docs:/docs jspecify-sphinx make -e SPHINXOPTS="-D language='ja'" html

      - uses: actions/upload-artifact@v1
        with:
          name: document
          path: docs/_build/html
