name: Update Reference Checker Conformance Test Reports

on:
  push:
    branches:
    - 'main'

env:
  reference_checker_repo: ${{ github.repository_owner }}/nullness-checker-for-checker-framework

defaults:
  run:
    shell: bash --noprofile --norc -e -o pipefail -x {0}

jobs:
  udpate-reference-checker-reports:
    name: Update reference checker conformance test reports if necessary
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow on ${{ env.reference_checker_repo }}
      run: |
        curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H "Authorization: Bearer ${TOKEN}"\
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          "https://api.github.com/repos/${reference_checker_repo}/dispatches" \
          -d '{"event_type":"update-conformance-test-reports","client_payload":{}}'
      env:
        TOKEN: ${{ secrets.REFERENCE_CHECKER_WORKFLOW_PAT }}
